const ACTION_TYPES = {
    ADD_REPO_BEGIN: "ADD_REPO_BEGIN",
    ADD_REPO_SUCCESS: "ADD_REPO_SUCCESS",
    ADD_USER_BEGIN: "ADD_USER_BEGIN",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS"
};

export default ACTION_TYPES;
